name: Deploy Azure Function (Python)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Facultatif) Vérifier les dépendances / lint rapide
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Déploiement: l'action embarque Core Tools, pas besoin de Node côté client
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-ollama-parquet
          package: ./src
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true